version: "3.3"
services:
  ci:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/www/html/gan-shmuel/billing:./billing/db
      - /var/www/html/gan-shmuel/weight:./weight/db
    environment:
      - MAIL_PASSWORD='12341234!'
      - MAIL_USERNAME='autmailer101@gmail.com'
    restart: unless-stopped
    labels:
      team: devops
      container: app
    
