version: "3.1"
services:
  web:
    build: ./app
    ports:
      - "8082:5000"
    volumes:
      - ./in:/in
  db:
    image: mysql:8.0
    ports:
      - "3306"
    volumes:
      - data:/var/lib/mysql
      - ./db/billingdb.sql:/docker-entrypoint-initdb.d/billingdb.sql
    environment:
      - "MYSQL_DATABASE=billdb"
      - "MYSQL_ROOT_PASSWORD=root"
    expose:
      - "3306"

volumes:
  data:
