version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "3306:3306"

  db:
    image: mysql:8.0.21
    ports:
      - "30000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
