version: '3.3'
services:
  app:
    build: ./app
    depends_on:
      - mysql
    ports: 
      - "${PORT}:5000"
    labels:
      team: weight
      container: app  
  
  mysql:
    image: mysql:8
    volumes: 
      - "./mysql-db/whl_db.sql:/docker-entrypoint-initdb.d/whl_db.sql"
    environment: 
      - MYSQL_ROOT_PASSWORD=123456
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    labels:
      team: weight
      container: db   
