version: "3"
services:
  app:
    build: ./app
    links:
      - weightDB
    ports:
      - "8084:5000"

  weightDB:
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./weightDB:/docker-entrypoint-initdb.d/:ro
