version: "3.1"
services:
  web:
    build: ./app
    ports:
      - "8082:5000"
  redis:
    image: "redis:alpine"
  db:
    build: ./db/dbDfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: billing_db
    ports:
      - "3306"
    volumes:
      - db_data_1:/var/lib/mysql

volumes: 
  db_data_1:
