version: "3.3"
services:
  ci:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      team: devops
      container: app