
version: '3.3'
services:
  app:
    build: ./app
    depends_on:
      - mysql
    ports: 
      - "8084:5000"
  
  mysql:
    image: mysql:8
    #container_name: mysql_db
    volumes: 
      - "./mysql-db/whi_db.sql.sql:/docker-entrypoint-initdb.d/whi_db.sql"
    environment: 
      - MYSQL_ROOT_PASSWORD=123456
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
