version: "3.1"
services:
  web:
    build: ./app
    ports:
      - "${PORT}:5000"
    volumes:
      - ./in:/in
    labels:
      team: billing
      container: app
    depends_on:
      - bdb
​
  bdb:
    image: mysql:8.0.21
    ports:
      - "3306"
    volumes:
      - data:/var/lib/mysql
      - ${VOLUME}:/docker-entrypoint-initdb.d/
    environment:
      - "MYSQL_DATABASE=billdb"
      - "MYSQL_ROOT_PASSWORD=root"
    expose:
      - "3306"   
    labels:
      team: billing
      container: db
​
volumes:
  data: