version: "2.1"
services:
  app:
    build: ./app
    links:
      - db
    ports: 
      - "${PORT}:5000"
    labels:
      team: weight
      container: app 
    depends_on:
            db:
                condition: service_healthy  

  db:
    image: mysql:8.0.21
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - wdata:/var/lib/mysql/:rw
      - ${VOLUME}:/docker-entrypoint-initdb.d/
      - ${TEAM_PATH}:/weight
      # - "./db/user.sql:/docker-entrypoint-initdb.d/user.sql"
      # - wdata:/var/lib/mysql 
    labels:
      team: weight
      container: db 
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10     
volumes:
    wdata: 