version: "3.1"
services:
  app:
    build: ./app
    links:
      - db
    ports: 
      - "${PORT}:5000"
    labels:
      team: weight
      container: app 
    depends_on:
      - db
  db:
    image: mysql:8.0.21
    ports:
      - "3306"
    environment:
      - "MYSQL_DATABASE=roytuts"
      - "MYSQL_ROOT_PASSWORD=123456"
    volumes:
      - wdata:/var/lib/mysql/:rw
      - ${VOLUME}:/docker-entrypoint-initdb.d/
      - ${TEAM_PATH}:/weight
      # - "./db/user.sql:/docker-entrypoint-initdb.d/user.sql"
    expose:
      - "3306"
    labels:
      team: weight
      container: db 
volumes:
  wdata: 